optimizer:
  sgd:
    lr: 1.0e-3
    momentum: 0.9
    weight_decay: 1.0e-6
  adagrad:
    lr: 1.0e-3
    lr_decay: 0
    weight_decay: 0
    eps: 1.0e-10
  rmsprop:
    lr: 1.0e-3
    alpha: 0.99
    lr_decay: 0
    weight_decay: 0
    eps: 1.0e-8
    momentum: 0
  adam:
    lr: 1.0e-3
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-8
    weight_decay: 1.0e-6
