dataset:
  max_height: 32
  max_width: 32
dataloader:
  batch_size: 64
  num_workers: 8
model:
  model_name: 'cnn_simple_32'
  cnn:
    name: cnn_simple_32
    version: cnn_simple_32
    pretrained: True
    feature_extract: False
train:
  seed: 0
  clip: 1
  n_epochs: 30
  root_ckpt_dir: './checkpoint'
  ckpt_dir: './checkpoint_all_6_no_feature_extract_simple_randomgauss'
optimizer:
  start_lr: 1.0e-3
  end_lr: 1.0e-11
  step_reduce_lr: 5
  weight_decay: 1.0e-5
  dropout: 0.5
