dataloader:
  batch_size: 64
  num_workers: 8
train:
  seed: 0
  clip: 1
  n_epochs: 100
  root_ckpt_dir: './checkpoint'
  ckpt_dir: './checkpoint_resnet50_regression'
regularization:
  dropout: 0.5
scheduler:
  step_reduce_lr: 5

