dataset:
  max_height: 32
  max_width: 32
dataloader:
  batch_size: 64
  num_workers: 8
model:
  model_name: 'mobilenet_v2'
  cnn:
    name: mobilenet_v2
    version: mobilenet_v2
    pretrained: True
    feature_extract: True
train:
  seed: 0
  clip: 1
  n_epochs: 50
  root_ckpt_dir: './checkpoint'
  ckpt_dir: './checkpoint_all_6_no_feature_extract_mobilenet_randomgauss'
optimizer:
  start_lr: 1.0e-4
  end_lr: 1.0e-11
  step_reduce_lr: 5
  weight_decay: 1.0e-6
  dropout: 0.8
