dataset:
  max_height: 224
  max_width: 224
dataloader:
  batch_size: 64
  num_workers: 8
model:
  model_name: 'resnet18'
  cnn:
    name: resnet18
    module: ResnetFE
    version: resnet18
    pretrained: True
    feature_extract: False
train:
  seed: 0
  clip: 1
  n_epochs: 100
  root_ckpt_dir: './checkpoint'
  ckpt_dir: './checkpoint_version'
optimizer:
  start_lr: 3.0e-4
  end_lr: 1.0e-11

  # weight_decay: 1.0e-6
  # dropout: 0.5
  weight_decay: 0
regularization:
  dropout: 0.5
scheduler:
  step_reduce_lr: 5
